use_frameworks!

platform :ios, '9.0'

target 'DDNetworking_Example' do
  pod 'DDNetworking', :path => '../'

  target 'DDNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
